name = "cnc-tools"
compatibility_date = "2025-12-17"

# next-on-pages outputs here
pages_build_output_dir = ".vercel/output/static"

[[r2_buckets]]
binding = "CNCTOOLS_BUCKET"
bucket_name = "cnc-tools"
preview_bucket_name = "cnc-tools-dev"
